---
version: "3"
networks:
  app:
services:
  postgresql:
    image: postgres:9.3
    ports:
      - "127.0.0.1::5432"
    volumes:
      - ./:/django
    environment:
      POSTGRES_PASSWORD: securethenewspassword
      POSTGRES_USER: securethenews
      POSTGRES_DB: securethenewsdb
    user: postgres
    networks:
      app:
        aliases:
          - db

  node:
    build:
      context: .
      dockerfile: docker/NodeDockerfile
      args:
        NODE_VER: 10.15.1-alpine
        USERID: ${UID:?err}
    volumes:
      - ./:/var/www/django
    working_dir: /var/www/django
    command: /bin/ash -c "npm install && touch .node_complete && gulp watch"
    user: ${UID:?err}
    networks:
      - app

  django:
    build:
      context: .
      dockerfile: docker/DevDjangoDockerfile
      args:
        USERID: ${UID:?err}
    depends_on:
      - node
      - postgresql
    environment:
      DJANGO_LOG_CONSOLE: "yes"
      DJANGO_DB_PASSWORD: securethenewspassword
      DJANGO_DB_USER: securethenews
      DJANGO_DB_NAME: securethenewsdb
      DJANGO_DB_PORT: 5432
      DJANGO_DB_HOST: db
      DJANGO_XMLTEST_OUTPUT: "yes"
      DEPLOY_ENV: dev
    working_dir: /django
    volumes:
      - ./:/django
      - ./logs:/django-logs
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      app:
        aliases:
          - app
