---
version: '3'
networks:
  app:
services:
  postgresql:
    image: postgres:9.5
    ports:
      - "5432"
    volumes:
      - ./:/django
    environment:
      POSTGRES_PASSWORD: securethenewspassword
      POSTGRES_USER: securethenews
      POSTGRES_DB: securethenewsdb
    user: postgres
    networks:
      app:
        aliases:
          - db

  django:
    build:
      context: .
      dockerfile: docker/ProdDjangoDockerfile
      args:
        NODE_VER: 10.15.1-alpine
    image: quay.io/freedomofpress/securethenews
    read_only: true
    environment:
      DJANGO_ALLOWED_HOSTS: "app localhost"
      DEPLOY_ENV: prod
      DJANGO_DB_HOST: db
      DJANGO_DB_PASSWORD: securethenewspassword
      DJANGO_DB_USER: securethenews
      DJANGO_DB_NAME: securethenewsdb
      DJANGO_DB_PORT: 5432
      DJANGO_STATIC_ROOT: /django-static
      DJANGO_MEDIA_ROOT: /django-media
      DJANGO_SETTINGS_MODULE: securethenews.settings.production
      DJANGO_SECRET_KEY: 002b5d76a026c29190c50e610a73516cb277f0abd07ae6233fbbe86f655abc5a
      DJANGO_LOG_CONSOLE: "true"
    depends_on:
      - postgresql
    working_dir: /django
    volumes:
      - ${HOST_STATIC_DIR:-stn-django-static}:/django-media
      - ${HOST_MEDIA_DIR:-stn-django-static}:/django-static
      - ${HOST_LOGS_DIR:-stn-django-logs}:/django-logs
    networks:
      app:
        aliases:
          - app

  nginx:
    image: nginx:1.14-alpine
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d/:ro
      - ${HOST_STATIC_DIR:-stn-django-static}:/django-media:ro
      - ${HOST_MEDIA_DIR:-stn-django-static}:/django-static:ro
    depends_on:
      - django
    ports:
      - "8080:8080"
    networks:
      app:
        aliases:
          - nginx

volumes:
  stn-django-static:
  stn-django-media:
  stn-django-logs:
