---
version: 2
jobs:
  build:
    machine: true
    working_directory: ~/securethenews
    steps:
      - checkout

      - run:
          name: Install testing pre-reqs
          command: |
            # Set python to 3.5.2
            pyenv global 3.5.2
            pip install -U pip
            pip install pipenv
            pipenv install

      - run:
          name: Check Python dependencies for CVEs
          command: |
            pipenv run make safety

      - run:
          name: linters on the source
          command: |
            pipenv run make lint

      - run:
          name: Static code analysis for vulnerabilities
          command: |
            pipenv run make bandit

      - run:
          name: Ensure we can build and run dev env
          command: |
            pipenv run make dev-init
            pipenv run docker-compose up -d
            echo "Wait for environemnt to come up completely"
            while ! curl --output /dev/null --silent --head --fail http://localhost:8000; do sleep 1 && echo -n .; done;
            pipenv run make app-tests-dev
            pipenv run docker-compose down

      - run:
          name: Ensure we can build and run prod env
          command: |
            pipenv run make build-prod-container
            pipenv run make run-prod-env
            echo "Wait for environemnt to come up completely"
            while ! curl --output /dev/null --silent --head --fail http://localhost:8080; do sleep 1 && echo -n .; done;
            make ci-go

      - store_test_results:
          path: ~/securethenews/test-results
