---
version: 2
jobs:
  build:
    machine: true
    working_directory: ~/securethenews
    steps:
      - checkout

      - run:
          name: Install testing pre-reqs
          command: |
            pip install -U pipenv pip
            pipenv install

      - run:
          name: Check Python dependencies for CVEs
          command: |
            pipenv run make safety

      - run:
          name: flake8 lint on the source
          command: |
            pipenv run make flake8

      - run:
          name: Static code analysis for vulnerabilities
          command: |
            pipenv run make bandit

      - run:
          name: Ensure we can build and run dev env
          command: |
            pipenv run make docker-compose up -d
            pipenv run make app-tests
            pipenv run docker-compose down

      - run:
          name: Ensure we can build and run prod env
          command: |
            pipenv run make build-prod-container
            pipenv run make run-prod-env
            make ci-go

      - store_test_results:
          path: ~/securethenews/test-results
