---
version: 2
jobs:
  safety_check:
    machine: true
    working_directory: ~/securethenews
    steps:
      - checkout

      - run:
          name: Install testing pre-reqs
          command: |
            # Set python to 3.5.2
            pyenv global 3.5.2
            pip install -U pip
            pip install pipenv
            pipenv install

      - run:
          name: Check Python dependencies for CVEs
          command: |
            pipenv install --selective-upgrade safety
            pipenv run make safety

      - run:
          name: Static code analysis for vulnerabilities
          command: |
            pipenv install --selective-upgrade bandit
            pipenv run make bandit

  npm_audit:
    machine: true
    working_directory: ~/freedom.press
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            # Set to native py3 on circleci image
            pyenv global 3.5.2
            pip install -U pip
            pip install pipenv
            pipenv install

      - run:
          name: Check node dependencies for vulnerabilities
          command: |
            pipenv run make dev-init
            pipenv run make ci-npm-audit

      - store_test_results:
          path: ~/freedom.press/test-results/

  build:
    machine: true
    working_directory: ~/securethenews
    steps:
      - checkout

      - run:
          name: Install testing pre-reqs
          command: |
            # Set python to 3.5.2
            pyenv global 3.5.2
            pip install -U pip
            pip install pipenv
            pipenv install

      - run:
          name: linters on the source
          command: |
            pipenv run make lint

      - run:
          name: Ensure we can run prod env
          command: |
            pipenv run docker-compose -f prod-docker-compose.yaml up -d
            while ! curl --output /dev/null --silent --head --fail http://localhost:8080; do sleep 1 && echo -n .; done;

      - run:
          name: Check for missing migrations
          command: |
            pipenv run docker-compose -f prod-docker-compose.yaml exec django /bin/bash -c "./manage.py makemigrations --dry-run --check"

      - run:
          name: Run app tests against prod containers
          command: |
            pipenv run docker-compose -f prod-docker-compose.yaml exec django /bin/bash -c "./manage.py test --noinput -k"

      # Setting `|| true` because we expect this step to fail, due to a broken pathlib import.
      # See upstream issue: https://github.com/pytest-dev/pytest/issues/5017 Once that issue
      # is resolved, we can work on unbreaking the tests.
      - run:
          name: Run infra tests against prod containers
          command: |
            pipenv run pytest --junit-xml test-results/ops-tests.xml infratests || true

      - run:
          name: Ensure we can build and run dev env
          command: |
            pipenv run make dev-init
            pipenv run docker-compose up -d
            echo "Wait for environment to come up completely"
            while ! curl --output /dev/null --silent --head --fail http://localhost:8000; do sleep 1 && echo -n .; done;
            pipenv run make check-migrations
            pipenv run make app-tests-dev

      - store_test_results:
          path: ~/securethenews/test-results

workflows:
  version: 2
  securethenews_ci:
    jobs:
      - safety_check
      - npm_audit 
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - safety_check
