---
version: 2
jobs:
  build:
    machine: true
    working_directory: ~/securethenews
    steps:
      - checkout

      - run:
          name: Install testing pre-reqs
          command: |
            virtualenv ~/.venv
            . ~/.venv/bin/activate
            pip install -r molecule/requirements.txt

      - run:
          name: Ensure Django service stands up
          command: |
            . ~/.venv/bin/activate
            make ci-go

      - store_test_results:
          path: ~/securethenews/test-results
